version: "3"

services:
  panini:
    container_name: panini
    image: node:18-alpine
    restart: unless-stopped
    volumes:
      - ./:/app
    entrypoint: sh -c "cd app && npm install && npm start"
